CREATE SEQUENCE seq_patient_id
  START WITH 51
  INCREMENT BY 1
  NOMAXVALUE
  NOCYCLE;
  
CREATE SEQUENCE seq_doctor_id
  START WITH 11
  INCREMENT BY 1
  NOMAXVALUE
  NOCYCLE;

CREATE SEQUENCE seq_appointment_id
  START WITH 21
  INCREMENT BY 1
  NOMAXVALUE
  NOCYCLE;

CREATE SEQUENCE seq_treatment_id
  START WITH 41
  INCREMENT BY 1
  NOMAXVALUE
  NOCYCLE;

CREATE SEQUENCE seq_bill_id
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCYCLE;


