DECLARE
  u_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO u_count
    FROM dba_users t
   WHERE t.username = 'FOGORVOSADMIN';
  IF u_count = 1
  THEN
    EXECUTE IMMEDIATE 'drop user FOGORVOSADMIN cascade';
  END IF;
END;

CREATE USER FOGORVOSADMIN
IDENTIFIED BY fogorvos 
DEFAULT TABLESPACE users 
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION TO FOGORVOSADMIN;
GRANT CREATE PROCEDURE TO FOGORVOSADMIN;
GRANT CREATE TABLE TO FOGORVOSADMIN;
GRANT CREATE VIEW TO FOGORVOSADMIN;
GRANT CREATE SEQUENCE TO FOGORVOSADMIN;
GRANT CREATE TRIGGER TO FOGORVOSADMIN;
GRANT CREATE TYPE TO FOGORVOSADMIN;
